### ISSUE TITLE
storj-farm ignores config.json

### ISSUE THREAD

**Issue by smilesvua** [Storj/farmer#12]
The wizard generates config with all atributes of storj-farm. I edit the config, for an exmaple change opscode from 01020202 to 01030303, but when I start storj-farm again with the config i see "{"type":"info","message":"subscribing to topic \"01020202\"","timestamp":"2016-04-12T08:11:36.571Z”}” but the topic should be “01030303"

**Comment by BlackDuck888** [comment]
ip and port seams also to be ignored.
