### ISSUE TITLE
self report wrong

### ISSUE THREAD

**Issue by littleskunk** [Storj/farmer#16]
This is my self report
```
{ storage: { free: 1, used: 12288 },
  bandwidth: { upload: 8.82, download: 18.44 },
  contact:
   Contact {
     protocol: '0.5.2',
     address: '10.0.3.8',
     port: 4000,
     nodeID: '36b8c204b49422a0868c4dd7f6c5b3511834dae4',
     lastSeen: 1460540261229 },
  payment: '1KwiUNH3x7sJHqWXH5afh2rhPXKnT5W7Ye' }
```

1.) Ip address is my local address. That ip is useless for you. I assume you need my WAN ip.
2.) Free storage 1 TB but the report send 1 Byte.
3.) 12288 used space. It should be 0 or is there a secrect file I can't see (~./.storj-farmer-cli/)
4.) My real bandwidth should be ~48MBit/s down and ~10MBit/s upload.

**Comment by lucvanbraekel** [comment]
About littleskunk's point 1, I agree.  I am on a LAN, doing port forwarding on my router, switching off tunneling in storjfarm's config.  When I put my external IP address in the config, I get an error when storjfarmer tries to listen on that IP, which of course doesn't work. When I put my local IP address in the config, the software can listen on that IP but what is reported to the outside world is wrong, like littleskunk's self report shows.

I applied the following temporary workaround: I defined a hostname on a dynamic DNS provider, let's call it abcd.dyndns.org, which points to my external IP address.  Let's say my internal IP address is 192.168.1.11. I add the following line to my /etc/hosts file:

> abcd.dyndns.org   192.168.1.11

And this trick seems to work, I get shards...

But I think the software should be modified. "address" in the config should always be the external IP address as it should be reported to the outside world, to be reachable.  But the software itself should listen for incoming connections on its own default or generic interface, be it 127.0.0.1 or 0.0.0.0 or whatever.

**Comment by lucvanbraekel** [comment]
To correct littleskunk's point 2, correct line 234 as follows:
old: `free: config.storage.size,`
new: `free: totalSpace,`

**Comment by littleskunk** [comment]
@lucvanbraekel pull request please :)

**Comment by gordonwritescode** [comment]
@littleskunk 

1. This should be resolved with the core updates, however if the report gets sent before hole punch or tunnel, then it will report the value in the config - not to worry the next report should be correct and it connected by your nodeID
2. I have a fix staged, will push shortly
3. Those bytes are probably the directories created inside the shards directory (i think directories are usually 4096b (at least on gnu/linux))
4. The bandwidth test needs work - the speed is limited to how quickly our little [myspeed](https://github.com/gordonwritescode/myspeed) server can pump out random bytes as well as how quickly your machine can do the same and can be affected by other tests happening simultaneously.

@lucvanbraekel

1. The core library now listens on `0.0.0.0` and advertises the value in the config, so you should be good to go now
2. Fixed L234

---

Will push changes shortly.
