### ISSUE TITLE
Info and Warnings

### ISSUE THREAD

**Issue by wizardofwhere** [Storj/farmer#18]
My storjfarmer client shows the following repeatedly

missing or empty reply from contact
 and
rpc call 67601b4e60fd8ada5ce0a6898a8bd575c0e53d89 timed out

I have a 5TB Seagate drive attached to the USB port of my laptop which is connected to a 6Mbps service

thx

**Comment by gordonwritescode** [comment]
Not to worry, peers will join and leave the network, these messages indicate your node tried to talk to a peer that is no longer reachable.

**Comment by gordonwritescode** [comment]
FYI these message will reduce greatly when https://github.com/Storj/core/pull/43 is finished.
