### ISSUE TITLE
NAT Failure using Pfsense router even when UPNP is enabled

### ISSUE THREAD

**Issue by bjames301** [Storj/farmer#23]
{"type":"warn","message":"could not connect to NAT device via UPnP","timestamp":"2016-04-26T16:59:36.881Z"}

{"type":"warn","message":"rpc call 3eddac6aaac0ac486dd279bca654231ff940fd21 timed out","timestamp":"2016-04-26T17:00:06.789Z"}
{"type":"error","message":"failed to find tunnels, reason: RPC with ID `3eddac6aaac0ac486dd279bca654231ff940fd21` timed out","timestamp":"2016-04-26T17:00:06.790Z"}

**Comment by gordonwritescode** [comment]
The first part of this log output is not critical, you will establish a tunnel (though if you have upnp enabled it shouldn't happen).

The second part is because the bridge has not been updated yet with the new tunneling protocol, which we are deploying right now.

**Comment by gordonwritescode** [comment]
For reference, we are using [node-nat-upnp](https://github.com/indutny/node-nat-upnp) to do port forwarding, so the bug is likely there. I'll add some better log information as to why the port mapping failed to help diagnose.

**Comment by bjames301** [comment]
Gordon,  Thank you for the update and details on what I am seeing. Please let me know if there is anything further I can do to assist you.

**Comment by smilesvua** [comment]
The same behavior with  Zyxel Keenetic Extra. Other applications work fine through that UPnP.

**Comment by littleskunk** [comment]
It is working with the latest version. Please update and try again.

Now you should get this:
Error: failed to establish tunnel, reason: No tunnelers were returned

**Comment by smilesvua** [comment]
"could not connect to NAT device via UPnP", Storj Share Mac OS, Zyxel Keenetic Extra (edited)
Other applications work fine.
Storj Share Version 0.7.5 
Protocol Version 0.6.10

**Comment by littleskunk** [comment]
slack user blackduck will setup a VM for me. That way I should be able to debug the issue with his upnp router.
