### ISSUE TITLE
tunnel port range ignored

### ISSUE THREAD

**Issue by littleskunk** [Storj/farmer#32]
My config:
```
  "network": {
    "address": "0.0.0.0",
    "port": 4000,
    "seeds": [
      "storj://api.storj.io:8443/593844dc7f0076a1aeda9a6b9788af17e67c1052"
    ],
    "opcodes": [...],
    "forward": true,
    "tunnels": 2,
    "gateways": {
      "min": 5001,
      "max": 5002
    }
  },
```

Tunnel ignores the range and start with port 4001
```
farmer:~# netstat -a
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 *:4000                  *:*                     LISTEN
tcp        0      0 *:4001                  *:*                     LISTEN
```

**Comment by littleskunk** [comment]
I changed tunnel port to random (farmer port is still 4000). Gateway min and max ignored.
```
root@farmer:~# netstat -a
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 *:45583                 *:*                     LISTEN
tcp        0      0 *:ssh                   *:*                     LISTEN
tcp        0      0 *:4000                  *:*                     LISTEN
```

**Comment by gordonwritescode** [comment]
I know this is a little confusing, but the tunnel port is for the tunnel *server*, and by default it binds to your network port + 1. The is the entry point for all clients to establish a tunnel. 

The *gateways* are the dedicated entry points for others to communicate with a client that is connected to the tunnel server.

**Comment by littleskunk** [comment]
Ok got it. Wait a moment with my config wizard pull request. I will add tunnel server port.

**Comment by lucvanbraekel** [comment]
So when my farmer runs on port 4000 and I want to offer 5 tunnels, it is wrong to run them on ports 4001 to 4005, because port 4001 is the entry point? So I'd better specify 4002 tot 4006 then?  Always leave network port +1 free and not include it in the specified gateway ports?

**Comment by gordonwritescode** [comment]
That's correct, unless you explicitly set the entry point to another port, which I believe skunk is going to add to the config wizard.
