### ISSUE TITLE
Error: not implemented

### ISSUE THREAD

**Issue by alphaonex86** [Storj/farmer#33]
Hello, I have this bug when I start it under gentoo:
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-04-28T15:01:25.943Z"}
{"level":"info","message":"node created with nodeID 4f4917c0cf411371245ef1499c00378330f74f00","timestamp":"2016-04-28T15:01:25.949Z"}
{"level":"info","message":"publishing message on topic \"0e01\"","timestamp":"2016-04-28T15:01:25.952Z"}
{"level":"info","message":"subscribing to topic \"0e01\"","timestamp":"2016-04-28T15:01:25.953Z"}
{"level":"info","message":"subscribing to topic \"0e00\"","timestamp":"2016-04-28T15:01:25.954Z"}
{"level":"info","message":"subscribing to topic \"0f01020202\"","timestamp":"2016-04-28T15:01:25.965Z"}
{"level":"info","message":"subscribing to topic \"0f02020202\"","timestamp":"2016-04-28T15:01:25.965Z"}
{"level":"info","message":"subscribing to topic \"0f03020202\"","timestamp":"2016-04-28T15:01:25.966Z"}
{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.6.3\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461855685972}","timestamp":"2016-04-28T15:01:25.972Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.1\",\"address\":\"api.storj.io\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461855686512}","timestamp":"2016-04-28T15:01:26.512Z"}
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: not implemented
    at Writable._write (_stream_writable.js:430:6)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Writable.write (_stream_writable.js:217:11)
    at WebSocket.<anonymous> (/usr/lib64/node_modules/storj-farmer/node_modules/myspeed/lib/client.js:51:18)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onbinary (/usr/lib64/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/WebSocket.js:848:10)
    at /usr/lib64/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/Receiver.js:628:18
    at /usr/lib64/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/Receiver.js:368:7
    at /usr/lib64/node_modules/storj-farmer/node_modules/myspeed/node_modules/ws/lib/PerMessageDeflate.js:249:5

**Comment by alphaonex86** [comment]
Need nodejs 4.4 minimum, dep to fix?

**Comment by gordonwritescode** [comment]
Which version of node are you running? Must be LTS release (4.x.x).
