### ISSUE TITLE
Timeout on unused tunnels/gateways?

### ISSUE THREAD

**Issue by Th3Van** [Storj/farmer#34]
I've been running SH (2.2.4 / 0.6.5) full node for a couple of hours and the numbers of tunnels was increasing steady, with a new tunnel/gateway about every ~5 min. But what about unused/dead tunnels? Are they being removed due to a timeout or closed as private nodes becomes offline? - if not, one could end up with a server full of unused/dead tunnels :)
I've been reading the https://storj.github.io/core/tutorial-tunnel-connections.html but i wasn't able to find anything about it.

[StorjShare - Timeout on unused tunnels.txt](https://github.com/Storj/farmer/files/241706/StorjShare.-.Timeout.on.unused.tunnels.txt)

**Comment by gordonwritescode** [comment]
Looks like the gateways are in fact not being closed when the corresponding tunnel closes: https://github.com/Storj/core/blob/master/lib/tunnel/server.js#L186

I'll issue a fix today. Thanks for reporting.
