### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by Th3Van** [Storj/farmer#35]
Looks like when SH tries to open a gateway port, it somehow tries to assign the same port to to more than one gateways/tunnel. It's like the gateway/tunnel request are coming in a bit to fast for SH to handle :)

---

{"level":"info","message":"you are configured to tunnel up to 100 connections","timestamp":"2016-04-29T10:04:16.938Z"}
{"level":"info","message":"node created with nodeID ffa9832be51582d4a64bd3b60fb8c6347346ab79","timestamp":"2016-04-29T10:04:16.951Z"}
{"level":"info","message":"publishing message on topic \"0e01\"","timestamp":"2016-04-29T10:04:16.958Z"}
{"level":"info","message":"subscribing to topic \"0e01\"","timestamp":"2016-04-29T10:04:16.959Z"}
{"level":"info","message":"subscribing to topic \"0e00\"","timestamp":"2016-04-29T10:04:16.962Z"}
{"level":"info","message":"subscribing to topic \"0f01030303\"","timestamp":"2016-04-29T10:04:16.989Z"}
{"level":"info","message":"subscribing to topic \"0f02030303\"","timestamp":"2016-04-29T10:04:16.990Z"}
{"level":"info","message":"subscribing to topic \"0f03030303\"","timestamp":"2016-04-29T10:04:16.992Z"}
{"level":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.6.5\",\"address\":\"162.243.110.37\",\"port\":4000,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1461924257013}","timestamp":"2016-04-29T10:04:17.013Z"}
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.5\",\"address\":\"127.0.0.1\",\"port\":0,\"nodeID\":\"5741e9fc33e82e00b098eb1abc0a5574a329b8fd\",\"lastSeen\":1461924257112}","timestamp":"2016-04-29T10:04:17.112Z"}
**{"level":"info","message":"opening gateway for 5741e9fc33e82e00b098eb1abc0a5574a329b8fd","timestamp":"2016-04-29T10:04:17.171Z"}**
{"level":"info","message":"received valid message from {\"protocol\":\"0.6.5\",\"address\":\"127.0.0.1\",\"port\":0,\"nodeID\":\"47f8c3e3cfb7dadb295da8f7a1feab72438d8e3c\",\"lastSeen\":1461924257176}","timestamp":"2016-04-29T10:04:17.176Z"}
**{"level":"info","message":"opening gateway for 47f8c3e3cfb7dadb295da8f7a1feab72438d8e3c","timestamp":"2016-04-29T10:04:17.241Z"}**
events.js:141
      throw er; // Unhandled 'error' event
      ^

**Error: listen EADDRINUSE :::7000**
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at TunnelGateway.open (/usr/lib/node_modules/storj-farmer/node_modules/storj/lib/tunnel/gateway.js:166:16)
    at TunnelServer.createGateway (/usr/lib/node_modules/storj-farmer/node_modules/storj/lib/tunnel/server.js:109:11)
    at Protocol._handleOpenTunnel (/usr/lib/node_modules/storj-farmer/node_modules/storj/lib/network/protocol.js:324:39)
    at Transport.protocol (/usr/lib/node_modules/storj-farmer/node_modules/storj/node_modules/kad/lib/hooks/protocol.js:33:12)
    at /usr/lib/node_modules/storj-farmer/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:607:21

[StorjShare - Error - listen EADDRINUSE.txt](https://github.com/Storj/farmer/files/242150/StorjShare.-.Error.-.listen.EADDRINUSE.txt)

**Comment by gordonwritescode** [comment]
Pseudo-resolved this by picking a random port within the given range instead of using the next lowest one. Won't resolve the issue in a deterministic manner (we'll need some sort of locking mechanism long-term), but should reduce the likelihood of this happening a bit.

**Comment by Th3Van** [comment]
Thank you very much Gordon, I'll do some more testing on my serverXX.storj.dk server farm. and report back to you if i find any more bugs.

Thank you (and the storj team) for doing such a great job on this project! - please! keep up the good work :)
Let me know if you (or anyone on the storj dev team) needs access to a server to do some some tests (Debian/Windows/Fedora/BSD/Ubuntu/CentOS..etc)
I have a bunch of servers just waiting for someone to access it and start using them :). They have all been placed on a /24 subnet (256 IPv4 IP's + /64 Ipv6 network (18,446,744,073,709,551,616 IPv6's)) and combined on a 10Gbit/s network. They have all 3 x 1000Mbit access to the internet.
https://www.dropbox.com/s/yl9tjqsy2f3om4x/storj.dk%20-%20server%20offer.pdf?dl=0

Regards,
The3van

**Comment by gordonwritescode** [comment]
I've been wondering who owned those hosts! Thanks for the kind words and for participating in the project!

That's some b33fy w4r3z you got there. I'm sure we can put it to good use!

Pinging @phutchins - our devops mastermind.

**Comment by phutchins** [comment]
Ah hah! @Th3Van we found you! We've definitely been wondering who the awesome owner of these hosts was...

And thats an awesome blade center you've got there! We very much appreciate the offer and I've got some ideas for how we could possibly use something like this in the future.

If you're running a number of hosts with Storj services on them, I'd love to hear your input on how we could improve/streamline the experience.

**Comment by Th3Van** [comment]
Hi @phutchins 

I put my answers in a PDF file instead on github. I hope that's ok with you.

https://www.dropbox.com/s/9w6g8ekxj43teyz/storj.dk%20-%20server%20offer%20-%20201605031831-109969165198997282.pdf?dl=0

Let me know what you think :)

Regards,
Th3Van

**Comment by phutchins** [comment]
@Th3Van, thanks for your feedback, and no, you didn't break anything. :) We noticed a bit more traffic from your nodes and were simply excited to see someone potentially running a large number of farmers!

We're pushing hard to get to the next milestone in our roadmap so we're heads down for a bit but after we return for air, we would like to increase our focus on the experience of installing, running and maintaining farmers and clusters of farmers.

That being said, your input and feedback as we move forward would be exactly what we're looking for. We want to make it super easy and straight forward to do what you're doing. Those dos/bash scripts that you speak of in your pdf are a large part of what we'll be working with. I have a number of ideas automation for installation, upgrading, etc.

We're glad to have you as part of our community and look forward to working with you in the near future!
