### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by lunokhod** [Storj/farmer#44]
In running the latest version of storjfarm on OSX
~~~~
Farmer: v2.2.7
Core:   v0.6.11
~~~~
I received the following error
~~~~
events.js:160
     throw er; // Unhandled 'error' event
     ^Error: EMFILE: too many open files, scandir '/Volumes/Lunokhod-backup/storj/shards/4b25bb119421a5b0e479676b1f9dafa621da9747/meta'
   at Error (native)
~~~~
The error occurred after downloading about 8 GB of shards. Restarting the client seems to have worked, and I am continuing to download shards (now up to about 12 GB).

**Comment by gordonwritescode** [comment]
https://github.com/Storj/core/issues/84
