### ISSUE TITLE
ENOENT: no such file or directory, scandir ... /shards/.../challenges or ... /shards/.../meta

### ISSUE THREAD

**Issue by lucvanbraekel** [Storj/farmer#45]
### Package Versions

```
Farmer: v2.2.7
Core:   v0.6.10
```

Replace the values below using the output from `node --version`.

```
v5.10.1
```

### Expected Behavior

Please describe the program's expected behavior.

When a shard folder is present but subfolders "challenges" or "meta" are not present for whatever reason (previous crash, previous restart?), storjfarm should not crash but continue.

### Actual Behavior

Program crashes and continues to crash after restart. 

```
Error: ENOENT: no such file or directory, scandir '/home/lvb/.storj-farmer-cli/shards/573cad0e1d24a9480dd677bbecd517e8d150a6b6/challenges'
    at Error (native)
```

or another example, with "meta" subfolder instead of "challenges" subfolder:

```
Error: ENOENT: no such file or directory, scandir '/home/lvb/.storj-farmer-cli/shards/5f1fad754171a218aa9d534976ca58c39610e839/meta'
    at Error (native)
```

Workaround is to manually delete the shard subfolder, e.g.

```
rm -rf /home/lvb/shards/573cad0e1d24a9480dd677bbecd517e8d150a6b6
```
after which the program is able to restart without a crash.

### Steps to Reproduce

It is unclear under what circumstances this error occurs. Something was interrupted at the time when the shard folder structure was built? Shards created by older versions of the program? Consequence of "too many open files"?

**Comment by gordonwritescode** [comment]
See https://github.com/Storj/core/issues/84
