### ISSUE TITLE
Storjfarm update: No such file or directory

### ISSUE THREAD

**Issue by MatteoCarotta** [Storj/farmer#46]
### Package Versions

```
Farmer: v2.2.6
Core:   v0.6.7
```

Replace the values below using the output from `node --version`.

```
v4.4.3
```

### Expected Behavior
```
Storjfarm updated and ready to work.
```
### Actual Behavior
```
Program got lost, or erased. It doesn't work.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. https://www.dropbox.com/s/mrhiehl7m6lqmkl/1_Installing_node_nodejs_npm_storj-farmer?dl=0
2. https://www.dropbox.com/s/o1z2pzfmq7qk1i9/2_Storj-farmer_log?dl=0
3. https://www.dropbox.com/s/u3ez2zh7gmyti1d/3_Updateing_Storj-farmer?dl=0

**Comment by littleskunk** [comment]
Last version we moved the telemetry out to an own telemetry module. That new module is not published to npm. Please install git to install the new telemetry module.

**Comment by MatteoCarotta** [comment]
I did, I intalled git and updated  storj-farmer but the command didn't work, actually it eresed the program folder.... or something like that ;)
I installed storj-farmer a second time, now it runs properly, update didn't

**Comment by littleskunk** [comment]
Close the issue please.
